Repository harshithtunuguntla/project-osus, pull requests merged in 2024-10, with the labels that each got.

#2 updated broken links in index html for documentation and knowmore
  templates/index.html
Labels: hacktoberfest-accepted

#3 Added Issue, PR Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation_upgrade.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question_discussion.md
  .github/ISSUE_TEMPLATE/ui_ux.md
  .github/PULL_REQUEST_TEMPLATE/pull_request.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2024

#5 404 page
  templates/404_page.html
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2024

#38 autofocus on url box issue #26
  templates/index.html
Labels: hacktoberfest-accepted

#43 Fix issue #10: Keyword Validation for URL Shortening
  .gitignore
  templates/index.html
Labels: hacktoberfest-accepted, hacktoberfest-2024

#78 Added icons for SMs
  readme.md
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-2024

#84 Updated sidebar
  templates/documentation.html
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-2024

#88 fix count
  app.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2024, hacktoberfest-2024

#89 Update whatsapp link in readme file
  readme.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2024, hacktoberfest-2024

#90 Fixed code issues
  templates/index.html
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2024, hacktoberfest-2024
